---
title: "Regularization - HepVu overdose data"
author: "Hashan Fernando"
date: "2024-01-31"
output: 
  html_document: 
    theme: lumen
---

```{r, include=FALSE}
library(sf)
library(mgcv)
library(PerformanceAnalytics)
library(dplyr)
library(ggplot2)
library(GGally) 
library(gratia)
library(caret)
library(Metrics)
library(glmnet)
library(reshape2)
```

```{r}
# Importing the dataset
tnRawHepvu <- st_read("/Users/h6x/ORNL/git/opioid-risk-index/tennessee/data/processed data/SVI2020 TN counties with death rate HepVu/SVI2020_TN_counties_with_death_rate_HepVu.shp")


# Getting the column names
column_names <- names(tnRawHepvu)
#print(column_names)

```

```{r}
# Divide the "NOD_Rate_2" column by 100
tnRawHepvu$NOD_Rate_2 <- tnRawHepvu$NOD_Rate_2 / 100
```

```{r}

# Filtering the data set
desired_columns <- c("EP_POV150","EP_UNEMP","EP_HBURD","EP_NOHSDP","EP_UNINSUR","EP_AGE65","EP_AGE17","EP_DISABL","EP_SNGPNT","EP_LIMENG","EP_MINRTY","EP_MUNIT","EP_MOBILE","EP_CROWD","EP_NOVEH","EP_GROUPQ","NOD_Rate_2")

filtered_data <- tnRawHepvu %>%
  select(one_of(desired_columns))

filtered_data2 <- tnRawHepvu %>%
  select(one_of(desired_columns))

filtered_data3 <- tnRawHepvu %>%
  select(one_of(desired_columns))

filtered_data <- st_drop_geometry(filtered_data)
```

```{r}
filtered_data
```

```{r}
# Splitting the dataset into features (X) and target variable (y)
X <- filtered_data[, !names(filtered_data) %in% "NOD_Rate_2"]  # Features
y <- filtered_data$NOD_Rate_2  # Target variable

# Set seed for reproducibility
set.seed(123)

# Create an index for splitting the data
index <- createDataPartition(filtered_data$NOD_Rate_2, p = 0.8, list = FALSE)


# Create training sets for features and target
X_train <- X[index, ]
y_train <- y[index]

X_train_matrix <- as.matrix(X_train)


# Create test sets for features and target
X_test <- X[-index, ]
y_test <- y[-index]


X_test_matrix <- as.matrix(X_test)
```

### Ridge Regression 

```{r}
### RIDGE REGRESSION ###
m_ridge <- glmnet(X_train, y_train,family = "poisson", alpha = 0)

```

```{r}
# plot model coefficients vs. shrinkage parameter lambda
plot_ridge <- plot(m_ridge, xvar = "lambda", label = TRUE, xlab = expression(paste("Log(", lambda, ")")))

```



```{r}


# /Users/h6x/ORNL/git/opioid-risk-index/washington dc/rcode/results/regularization dc HepVu
# Save the plot using ggsave
#ggsave("/Users/h6x/ORNL/git/opioid-risk-index/washington dc/rcode/results/regularization dc HepVu/ridge_coefficients_plot.png", plot_ridge)

grid <- 10^seq(10, -1, length = 100) # set lambda sequence
m_ridge_cv <- cv.glmnet(X_train_matrix,
                        y_train,
                        alpha = 0,
                        lambda = grid)
```

```{r}
plot(m_ridge_cv)

m_ridge_cv$lambda.min

m_ridge_cv$lambda.1se
```

```{r}
#my
fitR <- glmnet(X_train, y_train,family = "poisson", alpha = 0,lambda = m_ridge_cv$lambda.1se)
fitR$beta[,1]

# prediction for the training set
m_ridge_cv_pred_train <- predict(m_ridge_cv,
                                 X_train_matrix, s = "lambda.min")

# calculate RMSE on training set
print(paste("RMSE on training set:", rmse(m_ridge_cv_pred_train,
                                           y_train)
)
)

# prediction for the test set
m_ridge_cv_pred_test <- predict(m_ridge_cv,
                                X_test_matrix, s = "lambda.min")

# calculate RMSE for the test data set
print(paste("RMSE on test set:", rmse(m_ridge_cv_pred_test,
                                       y_test)
)
)

# Initialize model_outcome as an empty list if it doesn't exist
if (!exists("model_outcome")) {
  model_outcome <- list()
}


# store model object and results of RMSE in the `list` object named `model_outcome`
model_outcome[["m_ridge_cv"]] <- list("model" = m_ridge_cv,
                                      "rmse" =  data.frame("name" = "ridge regression",
                                                           "train_RMSE" = rmse(m_ridge_cv_pred_train,
                                                                                y_train),
                                                           "test_RMSE" = rmse(m_ridge_cv_pred_test,
                                                                               y_test)
                                      )
)


```

### Lasso Regression

```{r}
### LASSO REGRESSION ###
m_lasso <- glmnet(X_train, y_train,family = "poisson", alpha = 1)

# plot model coefficients vs. shrinkage parameter lambda
plot(m_lasso, xvar = "lambda", label = TRUE, xlab = expression(paste("Log(", lambda, ")")))

m_lasso_cv <- cv.glmnet(X_train_matrix, y_train, alpha = 1)

plot(m_lasso_cv)

m_lasso_cv$lambda.min

m_lasso_cv$lambda.1se


```


```{r}
#my
fit <- glmnet(X_train, y_train,family = "poisson", alpha = 1,lambda = m_lasso_cv$lambda.1se)

fit$beta[,1]


# prediction for the training set
m_lasso_cv_pred_train <- predict(m_lasso_cv, X_train_matrix, s = "lambda.min")

# calculate RMSE on training set
print(paste("RMSE on training set:",
            rmse(m_lasso_cv_pred_train,
                  y_train)
)
)

# prediction for the test set
m_lasso_cv_pred_test <- predict(m_lasso_cv, X_test_matrix, s = "lambda.min")

# calculate RMSE for the test data set
print(paste("RMSE on test set:",
            rmse(m_lasso_cv_pred_test,
                  y_test)
)
)


# store model object and results of RMSE in the `list` object named `model_outcome`
model_outcome[["m_lasso_cv"]] <- list("model" = m_lasso_cv,
                                      "rmse" =  data.frame("name" = "LASSO regression",
                                                           "train_RMSE" = rmse(m_lasso_cv_pred_train, y_train),
                                                           "test_RMSE" = rmse(m_lasso_cv_pred_test, y_test)
                                      )
)
```

```{r}
#  Final view

# extract matrix object
res_matrix <- do.call(rbind, model_outcome)

# extract data frame object
res_df <- do.call(rbind, res_matrix[, 2])


# melt to tidy data frame
df <- melt(res_df,
           id.vars = "name",
           measure.vars = c("train_RMSE",
                            "test_RMSE")
)

# plot
ggplot(data = df, aes(x = name, y = value, fill = variable)) +
  geom_bar(stat = "identity",
           position = position_dodge()
  ) +
  scale_fill_hue(name = "") +
  xlab("") + ylab("RMSE") +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1)
  )


```


### Session Info:
```{r}
sessionInfo()
```




